# Generated by Django 4.2.30 on 2026-05-22 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo_iso', models.CharField(max_length=2, unique=True)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuesto_calculado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('resultado_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pais')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
