# Generated by Django 4.2.30 on 2026-05-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_moneda'),
    ]

    operations = [
        migrations.RunSQL(
            # 1. El código SQL nativo para CREAR el Stored Procedure
            sql="""
            CREATE OR REPLACE FUNCTION calcular_total_recaudado(pais_id_param INT)
            RETURNS DECIMAL(12, 2) AS $$
            DECLARE
                total_recaudo DECIMAL(12, 2);
            BEGIN
                SELECT COALESCE(SUM(impuesto_calculado), 0.00)
                INTO total_recaudo
                FROM api_solicitudimpuesto
                WHERE pais_id = pais_id_param;
                
                RETURN total_recaudo;
            END;
            $$ LANGUAGE plpgsql;
            """,
            
            # 2. El código SQL para BORRARLO (Para deshacer cambios de forma segura)
            reverse_sql="DROP FUNCTION IF EXISTS calcular_total_recaudado(INT);"
        )
    ]