# Generated by Django 4.2.30 on 2026-05-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_crear_sp_recaudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_aplicado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('impuesto_calculado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
